// <auto-generated/>
using namespace System::Reflection;

[assembly:AssemblyTitleAttribute("Prajna.native")];
[assembly:AssemblyProductAttribute("Prajna")];
[assembly:AssemblyDescriptionAttribute("Prajna: A Distributed Functional Programming Platform for Interactive Big Data Analytics and Cloud Service Building")];
[assembly:AssemblyVersionAttribute("0.0.1.7")];
[assembly:AssemblyFileVersionAttribute("0.0.1.7")];
