// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Prajna.BasicServiceData")]
[assembly: AssemblyProductAttribute("Prajna")]
[assembly: AssemblyDescriptionAttribute("Prajna: A Distributed Functional Programming Platform for Interactive Big Data Analytics and Cloud Service Building")]
[assembly: AssemblyVersionAttribute("0.0.1.7")]
[assembly: AssemblyFileVersionAttribute("0.0.1.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1.7";
    }
}
