// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Prajna.BasicServiceData")]
[assembly: AssemblyProductAttribute("Prajna")]
[assembly: AssemblyDescriptionAttribute("Prajna: Cloud Service and Interactive Big Data Analytics")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
