// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("VMHub.Services.SampleRecogServerCSharp")]
[assembly: AssemblyProductAttribute("VMHub.Services")]
[assembly: AssemblyDescriptionAttribute("VMHub: Visual Media Hub")]
[assembly: AssemblyVersionAttribute("0.0.1.2")]
[assembly: AssemblyFileVersionAttribute("0.0.1.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1.2";
    }
}
